name: Logo and Favicon Generation

on:
  push:
    paths:
      - 'logo.svg'
  workflow_dispatch:

jobs:
  make-favicons:
    runs-on: ubuntu-latest

    steps:
      - name: install inkscape
        run: |
          sudo apt update
          sudo apt install inkscape

      - name: checkout code
        uses: actions/checkout@v3

      - name: convert files
        run: |
          inkscape -w 180 -h 180 logo.svg -o assets/apple-touch-icon.png
          inkscape -w 32 -h 32 logo.svg -o assets/favicon-32.png
          inkscape -w 192 -h 192 logo.svg -o assets/favicon-192.png

      - name: commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update favicons"
          git push
