name: Logo and Favicon Generation

on:
  push:
    paths:
      - 'logo.svg'
  workflow_dispatch:

jobs:
  make-favicons:
    runs-on: ubuntu-latest

    steps:
      - name: install inkscape
        run: |
          sudo apt-get update
          sudo apt-get install inkscape -y
          inkscape -V

      - name: checkout code
        uses: actions/checkout@v3

      - name: list files
        run: ls -la

      - name: convert files
        run: |
          inkscape --help

      - name: commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update favicons"
          git push
