name: Logo and Favicon Generation

on:
  workflow_dispatch:

jobs:
  make-favicons:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: update apt
        run: sudo apt update
        
      - name: install json parser
        run: sudo apt install jq -y
        
      - name: get favicons
        env:
          API_KEY: ${{ secrets.REALFAVICONGENERATOR_API_KEY }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"favicon_generation": {"api_key": "$API_KEY"}}' '@realfavicongenerator.json' https://realfavicongenerator.net/api/favicon
