name: Logo and Favicon Generation

on:
  push:
    paths:
      - 'logo.svg'
  workflow_dispatch:

jobs:
  make-favicons:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: update apt
        run: sudo apt update
        
      - name: install json parser
        run: sudo apt install jq -y
        
      - name: get favicons
        env:
          API_KEY: ${{ secrets.REALFAVICONGENERATOR_API_KEY }}
        run: |
          PACKAGE_URL=$(curl -X POST -H "Content-Type: application/json" -d '{"favicon_generation":{"api_key":"'"$API_KEY"'","master_picture":{"type":"url","url":"https://raw.githubusercontent.com/Tuetenk0pp/argon-webtrees-theme/master/logo.svg"},"files_location":{"type":"path","path":"/path/to/icons"},"favicon_design":{"desktop_browser":{},"ios":{"picture_aspect":"no_change","assets":{"ios6_and_prior_icons":false,"ios7_and_later_icons":true,"precomposed_icons":false,"declare_only_default_icon":true}},"windows":{"picture_aspect":"no_change","background_color":"#5e72e4","assets":{"windows_80_ie_10_tile":true,"windows_10_ie_11_edge_tiles":{"small":false,"medium":true,"big":true,"rectangle":false}}},"android_chrome":{"picture_aspect":"shadow","manifest":{"name":"Webtrees","display":"standalone","orientation":"portrait"},"assets":{"legacy_icon":true,"low_resolution_icons":false},"theme_color":"#fff"},"safari_pinned_tab":{"picture_aspect":"black_and_white","threshold":60,"theme_color":"#5e72e4"}},"settings":{"compression":"3","scaling_algorithm":"Mitchell","error_on_image_too_small":true,"readme_file":true,"html_code_file":false,"use_path_as_is":false},"versioning":{"param_name":"ver","param_value":"15Zd8"}}}' https://realfavicongenerator.net/api/favicon | jq -r .favicon_generation_result.favicon.package_url) || exit
          wget -O package.zip $PACKAGE_URL
      - name: move files into place
        run: |
          mkdir favicons -p
          unzip package.zip -u -d favicons/
          rm package.zip
          
      - name: commit files      
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update favicons"
          git push
